/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bottiglia-compress.glb --transform 
Files: public/bottiglia-compress.glb [1.75MB] > D:\workspace\1_projects\active-hop\bottiglia-compress-transformed.glb [93.31KB] (95%)
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Color, MeshStandardMaterial } from "three";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";
import { color } from "motion";

export function Model(props) {
  const group = React.useRef();

  const { nodes, materials, animations } = useGLTF(
    "/bottiglia-compress-transformed.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  const colorMap = useLoader(
    TextureLoader,
    "texture/ActiveHop_etichetta__01_drop.jpg"
  );

  useEffect(() => {
    materials.Etichetta.map = colorMap;
    colorMap.repeat.x = -1;
    colorMap.offset.x = 1;
    materials.Etichetta.needsUpdate = true;
    materials.Mat.color = new Color(0.94, 0.94, 0.94);
    materials.Mat.needsUpdate = true;
  }, [colorMap, materials]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[25, 25, 25]}
      position={[0, -2, 0]}
      rotation={[0, Math.PI / 2, 0]}
    >
      <group>
        <group name="Bottiglia">
          <mesh
            name="Tappo"
            geometry={nodes.Tappo.geometry}
            material={materials.Mat}
          />
        </group>
        <mesh
          name="Etichetta"
          geometry={nodes.Etichetta.geometry}
          material={materials.Etichetta}
          position={[0, 0.069, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          name="Bottiglia_1"
          geometry={nodes.Bottiglia_1.geometry}
          material={materials.Mat}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bottiglia-compress-transformed.glb");
